
spring:
  # datasource 数据源配置内容,对应DataSourceProperties配置属性类
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:

    # HikariCP 自定义配置,对应 HikariConfig 配置类
    hikari:
      minimum-idle: 10 # 池中维护的最小空闲连接数，默认为10个
      maximum-pool-size: 10 # 池中最大连接数，包括闲置和使用中的连接，默认为10个